# Generated by Django 5.1 on 2024-08-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_method", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                (
                    "description",
                    models.TextField(blank=True, max_length=750, null=True),
                ),
                ("bankName", models.CharField(blank=True, max_length=75, null=True)),
            ],
        ),
    ]
